
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
align_and_mean_movement_reference_split_1b.py

Pipeline:
  1) Load FaceMoCap CSV sequences (108 markers: 3 dental + 105 facial).
     - Skip first 5 rows
     - Ignore first 2 columns (time/frame metadata), use remaining numeric columns.
  2) Remove head motion by converting each frame to a per-frame dental-support coordinate system (markers 0..2).
  3) Choose a neutral frame as the most complete facial frame among the first `neutral_first_pct` of frames.
  4) Build template neutral as frame 0 of template CSV, converted to its own dental frame.
  5) Estimate robust rigid transform (facial-only correspondences) mapping target neutral -> template neutral:
       trimmed RANSAC + optional yaw flip + optional Huber refinement
     Apply optional fixed 90° rotations (canonical axis convention) CONSISTENTLY to both template and target
     before estimating the rigid transform.
  6) Apply the fitted transform to ALL frames => sequences aligned in the template frame (no head motion).
  7) Extract the active movement window using displacement-from-neutral energy (facial markers only).
  8) Temporally resample to `n_frames` (=100) with NaN-robust interpolation per marker coordinate.
  9) Compute the per-movement healthy representative dynamic point cloud as NaN-mean over reference-split healthy samples.
 10) Export reports + interactive Plotly HTML animations.

Outputs:
  out_dir/
    summary_sequences.csv
    M1/
      mean_healthy.npy
      mean_healthy.csv
      mean_healthy_animation.html
      sample_animation_<id>.html (optional, first N samples)
      diagnostics/
        energy_curves/...
        overlays/...
    ...

Notes:
  - Marker indexing assumes the FaceMoCap CSV yields 108 markers * 3 coords = 324 columns, after dropping 2 cols.
  - Robust to NaNs: permanent missing markers are ignored in fits and in means.
  - Requires a metadata column such as `reference_split`; by default only rows with
    reference_split == "reference" and condition == "healthy" are used.

Author: generated by ChatGPT (GPT-5.2 Thinking)
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

# Plotly is used for interactive HTML animations
import plotly.graph_objects as go


# ----------------------------
# Utilities
# ----------------------------

def ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)

def is_finite(a: np.ndarray) -> np.ndarray:
    return np.isfinite(a).all(axis=-1)

def safe_float(x) -> float:
    try:
        return float(x)
    except Exception:
        return float("nan")

def write_json(path: Path, obj) -> None:
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False))

def nanmean_keepdims(x: np.ndarray, axis=None, keepdims=False) -> np.ndarray:
    with np.errstate(all="ignore"):
        return np.nanmean(x, axis=axis, keepdims=keepdims)

def nanmedian(x: np.ndarray) -> float:
    with np.errstate(all="ignore"):
        return float(np.nanmedian(x))

def rms(x: np.ndarray) -> float:
    with np.errstate(all="ignore"):
        return float(np.sqrt(np.nanmean(np.square(x))))

def aggregate_reference_sequences(
    stack: np.ndarray,
    method: str = "mean",
    trim_frac: float = 0.10,
) -> np.ndarray:
    """
    Aggregate aligned healthy reference sequences across samples.

    stack shape: (N, T, 108, 3)
    method:
      - mean: current behavior, NaN-aware arithmetic mean
      - median: robust per-coordinate median
      - trimmed_mean: drops low/high sample quantiles per coordinate, then averages
    """
    method = method.strip().lower()
    with np.errstate(all="ignore"):
        if method == "mean":
            return np.nanmean(stack, axis=0)
        if method == "median":
            return np.nanmedian(stack, axis=0)
        if method == "trimmed_mean":
            if not 0.0 <= trim_frac < 0.5:
                raise ValueError("--aggregation_trim_frac must be >= 0 and < 0.5")
            if trim_frac == 0.0 or stack.shape[0] < 3:
                return np.nanmean(stack, axis=0)
            lo = np.nanquantile(stack, trim_frac, axis=0, keepdims=True)
            hi = np.nanquantile(stack, 1.0 - trim_frac, axis=0, keepdims=True)
            trimmed = np.where((stack >= lo) & (stack <= hi), stack, np.nan)
            return np.nanmean(trimmed, axis=0)
    raise ValueError(f"Unknown aggregation method: {method}")

def robust_scale(x: np.ndarray, axis=0) -> np.ndarray:
    med = np.nanmedian(x, axis=axis)
    mad = np.nanmedian(np.abs(x - np.expand_dims(med, axis=axis)), axis=axis)
    scale = 1.4826 * mad
    q25 = np.nanquantile(x, 0.25, axis=axis)
    q75 = np.nanquantile(x, 0.75, axis=axis)
    iqr_scale = (q75 - q25) / 1.349
    scale = np.where(np.isfinite(scale) & (scale > 1e-9), scale, iqr_scale)
    return np.where(np.isfinite(scale) & (scale > 1e-9), scale, 1e-9)

def compute_reference_envelope(
    stack: np.ndarray,
    center_seq: np.ndarray,
    dental_n: int,
    low_q: float,
    high_q: float,
    opp_tau: float = 0.2,
) -> pd.DataFrame:
    face = slice(dental_n, stack.shape[2])
    X = stack[:, :, face, :]
    C = center_seq[:, face, :]

    D = X - X[:, 0:1, :, :]
    Dc = C - C[0:1, :, :]

    mag = np.linalg.norm(D, axis=-1)              # N,T,M
    mag_c = np.linalg.norm(Dc, axis=-1)           # T,M
    amp = np.nanmax(mag, axis=1)                  # N,M

    diff = D - Dc[None, :, :, :]
    rmse = np.sqrt(np.nanmean(np.linalg.norm(diff, axis=-1) ** 2, axis=1))  # N,M

    dot = np.nansum(D * Dc[None, :, :, :], axis=-1)
    denom = (mag * mag_c[None, :, :]) + 1e-9
    cos_sim = dot / denom
    amp_gate = np.nanquantile(np.nanmax(mag_c, axis=0), 0.20)
    amp_gate = max(float(amp_gate), 1e-9)
    dir_ok = np.isfinite(cos_sim) & (mag >= amp_gate) & (mag_c[None, :, :] >= amp_gate)
    neg_part = np.where(dir_ok, np.maximum(0.0, -cos_sim), np.nan)
    w = np.where(dir_ok, np.minimum(mag, mag_c[None, :, :]), np.nan)
    opp_score = np.nansum(w * neg_part, axis=1) / (np.nansum(w, axis=1) + 1e-9)  # N,M
    opp_fraction = np.nanmean(dir_ok & (cos_sim < -opp_tau), axis=1)

    rows = []
    n_markers = X.shape[2]
    for j in range(n_markers):
        rows.append({
            "marker_id": int(j + dental_n),
            "facial_marker_id": int(j),
            "n_reference_samples": int(stack.shape[0]),
            "amp_median": float(np.nanmedian(amp[:, j])),
            "amp_low": float(np.nanquantile(amp[:, j], low_q)),
            "amp_high": float(np.nanquantile(amp[:, j], high_q)),
            "amp_scale": float(robust_scale(amp[:, j], axis=0)),
            "rmse_median": float(np.nanmedian(rmse[:, j])),
            "rmse_high": float(np.nanquantile(rmse[:, j], high_q)),
            "rmse_scale": float(robust_scale(rmse[:, j], axis=0)),
            "opp_score_median": float(np.nanmedian(opp_score[:, j])),
            "opp_score_high": float(np.nanquantile(opp_score[:, j], high_q)),
            "opp_score_scale": float(robust_scale(opp_score[:, j], axis=0)),
            "opp_fraction_median": float(np.nanmedian(opp_fraction[:, j])),
            "opp_fraction_high": float(np.nanquantile(opp_fraction[:, j], high_q)),
        })
    return pd.DataFrame(rows)

def trimmed_indices(residuals: np.ndarray, trim_frac: float) -> np.ndarray:
    """Return boolean mask of inliers as best (1-trim_frac) residuals. residuals shape (N,)."""
    n = residuals.shape[0]
    if n == 0:
        return np.zeros((0,), dtype=bool)
    k = max(1, int(round((1.0 - trim_frac) * n)))
    order = np.argsort(residuals)
    inl = np.zeros((n,), dtype=bool)
    inl[order[:k]] = True
    return inl

def rotation_matrix_from_axis_angle(axis: np.ndarray, angle_rad: float) -> np.ndarray:
    axis = np.asarray(axis, dtype=float)
    norm = np.linalg.norm(axis)
    if norm < 1e-12:
        return np.eye(3)
    axis = axis / norm
    x, y, z = axis
    c = math.cos(angle_rad)
    s = math.sin(angle_rad)
    C = 1 - c
    return np.array([
        [c + x*x*C, x*y*C - z*s, x*z*C + y*s],
        [y*x*C + z*s, c + y*y*C, y*z*C - x*s],
        [z*x*C - y*s, z*y*C + x*s, c + z*z*C],
    ], dtype=float)

def fixed_rot_xyz(deg_xyz: Tuple[float, float, float]) -> np.ndarray:
    """Rotation matrix for successive rotations around X then Y then Z (degrees)."""
    rx, ry, rz = [math.radians(d) for d in deg_xyz]
    Rx = rotation_matrix_from_axis_angle(np.array([1,0,0]), rx)
    Ry = rotation_matrix_from_axis_angle(np.array([0,1,0]), ry)
    Rz = rotation_matrix_from_axis_angle(np.array([0,0,1]), rz)
    return Rz @ Ry @ Rx  # common convention: apply X then Y then Z to column vectors


# ----------------------------
# FaceMoCap CSV loading
# ----------------------------

def load_facemocap_csv(csv_path: Path, skiprows: int = 5, drop_first_cols: int = 2) -> np.ndarray:
    """
    Returns: frames x 108 x 3 float array with NaNs where missing.
    Assumes after dropping first `drop_first_cols`, remaining columns are 108*3.
    """
    df = pd.read_csv(csv_path, skiprows=skiprows, header=None)
    if df.shape[1] <= drop_first_cols:
        raise ValueError(f"CSV has too few columns: {df.shape[1]} in {csv_path}")
    arr = df.iloc[:, drop_first_cols:].to_numpy(dtype=float, copy=True)
    ncols = arr.shape[1]
    if ncols % 3 != 0:
        raise ValueError(f"Expected columns multiple of 3 after dropping {drop_first_cols}, got {ncols} in {csv_path}")
    n_markers = ncols // 3
    if n_markers < 108:
        # Allow fewer markers but expect at least 108 in this project; warn by error to avoid silent misparse.
        raise ValueError(f"Expected at least 108 markers (324 cols), got {n_markers} markers in {csv_path}")
    if n_markers > 108:
        # Some exports may include extra columns; keep first 108 markers.
        arr = arr[:, :108*3]
        n_markers = 108
    frames = arr.reshape(arr.shape[0], n_markers, 3)
    return frames


# ----------------------------
# Dental frame conversion
# ----------------------------

@dataclass
class DentalFrame:
    R: np.ndarray  # 3x3 rotation matrix
    o: np.ndarray  # 3 translation origin

def compute_dental_frame(d: np.ndarray) -> Optional[DentalFrame]:
    """
    Compute a right-handed orthonormal frame from 3 dental markers d shape (3,3).
    Returns None if degenerate / NaN.
    """
    if d.shape != (3,3):
        raise ValueError("dental markers must be (3,3)")
    if not np.isfinite(d).all():
        return None
    o = d.mean(axis=0)

    x = d[1] - d[0]
    nx = np.linalg.norm(x)
    if nx < 1e-8:
        return None
    x = x / nx

    v = d[2] - d[0]
    # normal to dental plane
    z = np.cross(x, v)
    nz = np.linalg.norm(z)
    if nz < 1e-8:
        return None
    z = z / nz

    y = np.cross(z, x)
    ny = np.linalg.norm(y)
    if ny < 1e-8:
        return None
    y = y / ny

    R = np.stack([x, y, z], axis=1)  # columns are basis vectors in world coords
    # Ensure R is proper rotation
    if np.linalg.det(R) < 0:
        # Flip z to make det positive
        R[:, 2] *= -1.0
    return DentalFrame(R=R, o=o)

def world_to_dental(frames_world: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """
    Convert each frame to dental coordinates using per-frame dental frame.
    Returns:
      frames_dental: (T,108,3) in dental coords
      ok_mask: (T,) whether dental frame was valid
    """
    T = frames_world.shape[0]
    out = np.full_like(frames_world, np.nan, dtype=float)
    ok = np.zeros((T,), dtype=bool)
    for t in range(T):
        d = frames_world[t, 0:3, :]
        fr = compute_dental_frame(d)
        if fr is None:
            continue
        ok[t] = True
        # P_d = R^T (P - o)
        out[t] = (fr.R.T @ (frames_world[t] - fr.o).T).T
    return out, ok

def dental_marker_drift(frames_dental: np.ndarray) -> float:
    """RMS drift of the 3 dental markers in dental coordinates over time (should be small)."""
    d = frames_dental[:, 0:3, :]  # T,3,3
    # center per frame
    with np.errstate(all="ignore"):
        d0 = d - np.nanmean(d, axis=1, keepdims=True)
    # compute per-frame magnitude
    mag = np.sqrt(np.nansum(d0**2, axis=-1))  # T,3
    return rms(mag)


# ----------------------------
# Neutral selection (new)
# ----------------------------

def pick_neutral_frame_most_complete(frames_dental: np.ndarray, first_pct: float, facial_slice: slice) -> int:
    """
    Pick the frame with maximum number of finite facial markers among first `first_pct` of frames.
    """
    T = frames_dental.shape[0]
    n_first = max(1, int(math.ceil(first_pct * T)))
    sub = frames_dental[:n_first, facial_slice, :]  # n_first,105,3
    finite = np.isfinite(sub).all(axis=-1)  # n_first,105
    counts = finite.sum(axis=1)  # n_first
    best = int(np.argmax(counts))
    if counts[best] == 0:
        raise ValueError("Neutral selection failed: no finite facial markers in early frames after dental-frame conversion.")
    return best


# ----------------------------
# Robust rigid alignment (facial only)
# ----------------------------

def kabsch(P: np.ndarray, Q: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """
    Compute rigid transform (R,t) s.t. R P + t ~= Q, using Kabsch.
    P,Q: Nx3 with finite values.
    """
    Pc = P.mean(axis=0)
    Qc = Q.mean(axis=0)
    X = P - Pc
    Y = Q - Qc
    H = X.T @ Y
    U, S, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
    if np.linalg.det(R) < 0:
        Vt[-1, :] *= -1
        R = Vt.T @ U.T
    t = Qc - R @ Pc
    return R, t

def apply_rt(points: np.ndarray, R: np.ndarray, t: np.ndarray) -> np.ndarray:
    return (R @ points.T).T + t

def trimmed_ransac_rigid(P: np.ndarray, Q: np.ndarray, trials: int, subset: int, trim_frac: float, rng: np.random.Generator) -> Tuple[np.ndarray, np.ndarray, np.ndarray, float]:
    """
    Robust rigid transform using trimmed-consensus RANSAC.
    Returns R,t,inlier_mask,trimmed_rms
    """
    n = P.shape[0]
    if n < max(3, subset):
        raise ValueError(f"Not enough correspondences for RANSAC: {n}")
    best_score = float("inf")
    best_R = None
    best_t = None
    best_inl = None

    idx_all = np.arange(n)
    for _ in range(trials):
        idx = rng.choice(idx_all, size=subset, replace=False)
        try:
            R, t = kabsch(P[idx], Q[idx])
        except np.linalg.LinAlgError:
            continue
        P2 = apply_rt(P, R, t)
        res = np.linalg.norm(P2 - Q, axis=1)
        inl = trimmed_indices(res, trim_frac)
        score = rms(res[inl])
        if score < best_score:
            best_score = score
            best_R, best_t, best_inl = R, t, inl

    if best_R is None:
        raise ValueError("RANSAC failed to produce a valid transform.")

    # Refit on inliers
    R, t = kabsch(P[best_inl], Q[best_inl])
    P2 = apply_rt(P, R, t)
    res = np.linalg.norm(P2 - Q, axis=1)
    inl = trimmed_indices(res, trim_frac)
    score = rms(res[inl])
    return R, t, inl, score

def huber_irls_refine(P: np.ndarray, Q: np.ndarray, R0: np.ndarray, t0: np.ndarray, inl_mask: np.ndarray, iters: int, k: float) -> Tuple[np.ndarray, np.ndarray]:
    """
    Simple IRLS-like refinement: iteratively reweight points by Huber weights and solve weighted Kabsch
    on inliers only. Guard against NaNs and SVD non-convergence.
    """
    R, t = R0.copy(), t0.copy()
    P_inl = P[inl_mask]
    Q_inl = Q[inl_mask]
    if P_inl.shape[0] < 3:
        return R, t

    w = np.ones((P_inl.shape[0],), dtype=float)
    for _ in range(iters):
        P2 = apply_rt(P_inl, R, t)
        r = np.linalg.norm(P2 - Q_inl, axis=1)
        # Huber weights
        w = np.where(r <= k, 1.0, (k / (r + 1e-12)))
        if not np.isfinite(w).all():
            break
        # weighted centroids
        sw = np.sum(w)
        if sw < 1e-12:
            break
        Pc = np.sum(P_inl * w[:, None], axis=0) / sw
        Qc = np.sum(Q_inl * w[:, None], axis=0) / sw
        X = P_inl - Pc
        Y = Q_inl - Qc
        H = (X * w[:, None]).T @ Y
        if not np.isfinite(H).all():
            break
        try:
            U, S, Vt = np.linalg.svd(H)
        except np.linalg.LinAlgError:
            break
        Rn = Vt.T @ U.T
        if np.linalg.det(Rn) < 0:
            Vt[-1, :] *= -1
            Rn = Vt.T @ U.T
        tn = Qc - Rn @ Pc
        R, t = Rn, tn
    return R, t

def maybe_yaw_flip(P: np.ndarray, Q: np.ndarray, R: np.ndarray, t: np.ndarray, axis: str) -> Tuple[np.ndarray, np.ndarray, bool, float]:
    """Try a 180° flip about one axis in target space before applying R,t; keep best by RMS."""
    axis = axis.upper()
    if axis not in ("X","Y","Z"):
        return R, t, False, float("inf")

    Rflip = np.eye(3)
    ax = {"X": np.array([1,0,0]), "Y": np.array([0,1,0]), "Z": np.array([0,0,1])}[axis]
    Rflip = rotation_matrix_from_axis_angle(ax, math.pi)

    # Option A: no flip
    resA = np.linalg.norm(apply_rt(P, R, t) - Q, axis=1)
    scoreA = rms(resA)

    # Option B: flip P first
    Pf = (Rflip @ P.T).T
    resB = np.linalg.norm(apply_rt(Pf, R, t) - Q, axis=1)
    scoreB = rms(resB)

    if scoreB < scoreA:
        # absorb flip into R: R*(Rflip*P) = (R*Rflip)P
        return (R @ Rflip), t, True, scoreB
    return R, t, False, scoreA


# ----------------------------
# Movement extraction + temporal resampling
# ----------------------------

def displacement_energy(frames_aligned: np.ndarray, neutral_idx: int, facial_slice: slice) -> np.ndarray:
    """
    Energy per frame based on facial displacement magnitude from neutral.
    Returns E shape (T,)
    """
    P0 = frames_aligned[neutral_idx, facial_slice, :]  # 105x3
    P = frames_aligned[:, facial_slice, :]
    with np.errstate(all="ignore"):
        d = P - P0[None, :, :]
        mag = np.sqrt(np.nansum(d**2, axis=-1))  # T,105
        E = np.nanmean(mag, axis=1)  # T
    return E

def extract_active_window(E: np.ndarray, neutral_idx: int, thr_percentile: float = 70.0, min_len: int = 10) -> Tuple[int,int]:
    """
    Extract contiguous active window around the maximum energy.
    Uses threshold as percentile of E (finite values). Returns [start,end] inclusive indices.
    """
    finite = np.isfinite(E)
    if finite.sum() == 0:
        return 0, len(E)-1
    thr = np.nanpercentile(E, thr_percentile)
    peak = int(np.nanargmax(E))
    active = (E >= thr) & finite
    if not active.any():
        return 0, len(E)-1

    # Find contiguous segment containing peak; else fallback to peak-neighborhood
    idx = np.where(active)[0]
    # Build segments
    segments = []
    s = idx[0]
    prev = idx[0]
    for i in idx[1:]:
        if i == prev + 1:
            prev = i
        else:
            segments.append((s, prev))
            s = i
            prev = i
    segments.append((s, prev))

    seg = None
    for a,b in segments:
        if a <= peak <= b:
            seg = (a,b)
            break
    if seg is None:
        seg = max(segments, key=lambda ab: ab[1]-ab[0])

    start, end = seg
    if (end - start + 1) < min_len:
        # Expand symmetrically
        half = (min_len - (end - start + 1)) // 2 + 1
        start = max(0, start - half)
        end = min(len(E)-1, end + half)
    return int(start), int(end)

def resample_sequence_nan_robust(frames: np.ndarray, start: int, end: int, n_frames: int) -> np.ndarray:
    """
    Resample frames[start:end+1] to n_frames using linear interpolation per marker coordinate.
    frames: (T,108,3)
    returns: (n_frames,108,3)
    """
    seg = frames[start:end+1]
    Tseg = seg.shape[0]
    if Tseg == 1:
        return np.repeat(seg, n_frames, axis=0)

    t_old = np.linspace(0.0, 1.0, Tseg)
    t_new = np.linspace(0.0, 1.0, n_frames)
    out = np.full((n_frames, seg.shape[1], 3), np.nan, dtype=float)

    # For each marker and coord, interpolate over finite points
    for m in range(seg.shape[1]):
        for c in range(3):
            y = seg[:, m, c]
            finite = np.isfinite(y)
            if finite.sum() < 2:
                # keep NaN or constant if one point exists
                if finite.sum() == 1:
                    out[:, m, c] = y[finite][0]
                continue
            out[:, m, c] = np.interp(t_new, t_old[finite], y[finite])
    return out


# ----------------------------
# Plotly animation
# ----------------------------

def make_animation_html(points_seq: np.ndarray, out_html: Path, title: str, facial_only: bool = True, marker_size: int = 3) -> None:
    """
    Create interactive 3D animation (slider + play) and save as HTML.
    points_seq: (T,108,3) or (T,105,3) if facial_only already.
    """
    seq = points_seq.copy()
    if facial_only and seq.shape[1] == 108:
        seq = seq[:, 3:, :]  # facial only

    # Determine axis ranges from finite points
    finite = np.isfinite(seq).all(axis=-1)
    pts = seq[finite]
    if pts.size == 0:
        # produce empty
        fig = go.Figure()
        fig.update_layout(title=title)
        fig.write_html(str(out_html), include_plotlyjs="cdn")
        return

    mins = np.nanmin(pts, axis=0)
    maxs = np.nanmax(pts, axis=0)
    pad = 0.05 * np.max(maxs - mins)
    xr = [float(mins[0]-pad), float(maxs[0]+pad)]
    yr = [float(mins[1]-pad), float(maxs[1]+pad)]
    zr = [float(mins[2]-pad), float(maxs[2]+pad)]

    frames = []
    for i in range(seq.shape[0]):
        P = seq[i]
        ok = np.isfinite(P).all(axis=1)
        frames.append(go.Frame(
            data=[go.Scatter3d(
                x=P[ok,0], y=P[ok,1], z=P[ok,2],
                mode="markers",
                marker=dict(size=marker_size),
            )],
            name=str(i)
        ))

    # initial
    P0 = seq[0]
    ok0 = np.isfinite(P0).all(axis=1)
    fig = go.Figure(
        data=[go.Scatter3d(
            x=P0[ok0,0], y=P0[ok0,1], z=P0[ok0,2],
            mode="markers",
            marker=dict(size=marker_size),
        )],
        frames=frames
    )

    # slider
    steps = []
    for i in range(seq.shape[0]):
        steps.append(dict(
            method="animate",
            args=[[str(i)], dict(mode="immediate", frame=dict(duration=0, redraw=True), transition=dict(duration=0))],
            label=str(i)
        ))

    fig.update_layout(
        title=title,
        scene=dict(
            xaxis=dict(range=xr),
            yaxis=dict(range=yr),
            zaxis=dict(range=zr),
            aspectmode="data",
        ),
        updatemenus=[dict(
            type="buttons",
            showactive=False,
            buttons=[
                dict(label="Play", method="animate",
                     args=[None, dict(frame=dict(duration=50, redraw=True), transition=dict(duration=0), fromcurrent=True, mode="immediate")]),
                dict(label="Pause", method="animate",
                     args=[[None], dict(frame=dict(duration=0, redraw=True), transition=dict(duration=0), mode="immediate")]),
            ],
        )],
        sliders=[dict(
            active=0,
            currentvalue=dict(prefix="Frame: "),
            pad=dict(t=50),
            steps=steps,
        )]
    )

    fig.write_html(str(out_html), include_plotlyjs="cdn")


# ----------------------------
# Metadata parsing
# ----------------------------

def infer_cols(df: pd.DataFrame) -> Tuple[str, str, str]:
    cols = [c.strip() for c in df.columns]
    lower = {c: c.lower() for c in cols}

    # path column
    path_candidates = ["complete_filepath", "filepath", "path", "csv_path", "relpath", "relative_path", "file", "fullpath"]
    path_col = None
    for cand in path_candidates:
        for c in cols:
            if lower[c] == cand:
                path_col = c
                break
        if path_col:
            break
    if path_col is None:
        raise ValueError("Could not infer file path column in metadata (expected complete_filepath or similar).")

    # movement column
    mov_candidates = ["facial_movement", "movement", "mov", "m", "single_movement", "movement_id"]
    mov_col = None
    for cand in mov_candidates:
        for c in cols:
            if lower[c] == cand:
                mov_col = c
                break
        if mov_col:
            break
    if mov_col is None:
        raise ValueError("Could not infer movement column in metadata (expected facial_movement or similar).")

    # group / condition column
    grp_candidates = ["condition", "group", "label", "is_healthy"]
    grp_col = None
    for cand in grp_candidates:
        for c in cols:
            if lower[c] == cand:
                grp_col = c
                break
        if grp_col:
            break
    if grp_col is None:
        raise ValueError("Could not infer condition/group column in metadata (expected condition).")

    return path_col, mov_col, grp_col

def normalize_movement(m) -> str:
    """
    Returns movement label like 'M1'..'M5' from either numeric or string.
    """
    if isinstance(m, str):
        s = m.strip()
        if s.upper().startswith("M"):
            return "M" + "".join([ch for ch in s[1:] if ch.isdigit()])
        # numeric string
        if s.isdigit():
            return f"M{int(s)}"
        return s
    try:
        return f"M{int(m)}"
    except Exception:
        return str(m)

def is_healthy_from_condition(v) -> bool:
    if isinstance(v, (bool, np.bool_)):
        return bool(v)
    s = str(v).strip().lower()
    return s in ("healthy", "sain", "control", "controls", "0", "false?")  # conservative

def print_split_subjects(df: pd.DataFrame, split_col: str, split_label: str, grp_col: str) -> None:
    participants = sorted(df["participant_id"].astype(str).str.strip().unique()) if "participant_id" in df.columns else []
    print("\nReference cohort used for mean_healthy.npy")
    print(f"  split column: {split_col}")
    print(f"  split label: {split_label}")
    print(f"  condition: healthy")
    print(f"  participants ({len(participants)}): {', '.join(participants) if participants else '<none>'}")

    if "mov_norm" in df.columns:
        counts = (
            df.groupby(["mov_norm", grp_col, split_col], dropna=False)
            .size()
            .rename("n_rows")
            .reset_index()
            .sort_values(["mov_norm", grp_col, split_col])
        )
        print("\nReference rows by movement")
        print(counts.to_string(index=False))

# ----------------------------
# Main
# ----------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--metadata", required=True, type=str)
    ap.add_argument("--template_csv", required=True, type=str)
    ap.add_argument("--out_dir", required=True, type=str)
    ap.add_argument("--root_override", default=None, type=str)
    ap.add_argument("--movements", nargs="+", default=["M1","M2","M3","M4","M5"])
    ap.add_argument("--reference_split_col", default="reference_split", type=str)
    ap.add_argument("--reference_split_label", default="reference", type=str)
    ap.add_argument("--aggregation", choices=["mean", "median", "trimmed_mean"], default="mean",
                    help="How to aggregate healthy reference sequences into mean_healthy.npy.")
    ap.add_argument("--aggregation_trim_frac", type=float, default=0.10,
                    help="Fraction trimmed from each tail when --aggregation trimmed_mean.")
    ap.add_argument("--envelope_low_quantile", type=float, default=0.05,
                    help="Lower reference amplitude envelope quantile for hypokinesia.")
    ap.add_argument("--envelope_high_quantile", type=float, default=0.95,
                    help="Upper reference envelope quantile for hyper/abnormal/counter-direction.")
    ap.add_argument("--dental_n", type=int, default=3,
                    help="Number of dental markers before facial markers.")
    ap.add_argument("--neutral_first_pct", type=float, default=0.05)
    ap.add_argument("--n_frames", type=int, default=100)
    ap.add_argument("--energy_thr_percentile", type=float, default=70.0)
    ap.add_argument("--min_window_len", type=int, default=10)

    ap.add_argument("--min_points", type=int, default=60)

    ap.add_argument("--ransac", action="store_true")
    ap.add_argument("--ransac_trials", type=int, default=4000)
    ap.add_argument("--ransac_subset", type=int, default=4)
    ap.add_argument("--trim_frac", type=float, default=0.10)

    ap.add_argument("--try_yaw_flip", action="store_true")
    ap.add_argument("--yaw_flip_axis", type=str, default="Z")

    ap.add_argument("--huber_iters", type=int, default=3)
    ap.add_argument("--huber_k", type=float, default=1.5)

    ap.add_argument("--fixed_rot_xyz", nargs=3, type=float, default=[90.0, 90.0, 90.0])

    ap.add_argument("--n_show", type=int, default=10)
    ap.add_argument("--export_sample_anims", type=int, default=3, help="Per movement, export this many sample animations in addition to mean.")
    ap.add_argument("--seed", type=int, default=0)

    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    ensure_dir(out_dir)

    # Parse metadata
    df = pd.read_csv(args.metadata)
    path_col, mov_col, grp_col = infer_cols(df)

    # optional filters
    if "valid_for_processing" in df.columns:
        df = df[df["valid_for_processing"].astype(int) == 1].copy()
    if "single_movement" in df.columns:
        df = df[df["single_movement"].astype(int) == 1].copy()

    df["mov_norm"] = df[mov_col].apply(normalize_movement)
    wanted = set([m.upper() for m in args.movements])
    df = df[df["mov_norm"].str.upper().isin(wanted)].copy()

    if args.reference_split_col not in df.columns:
        raise ValueError(
            f"Metadata must contain '{args.reference_split_col}'. "
            "Run make_reference_split.py first, or pass --reference_split_col."
        )

    split = df[args.reference_split_col].astype(str).str.strip().str.lower()
    cond = df[grp_col].astype(str).str.strip().str.lower()
    reference_label = args.reference_split_label.strip().lower()
    df = df[(split == reference_label) & (cond == "healthy")].copy()
    if df.empty:
        raise ValueError(
            "No usable healthy reference rows remain after filtering by "
            f"{args.reference_split_col} == {args.reference_split_label!r}, "
            "condition == 'healthy', valid_for_processing == 1, "
            "single_movement == 1, and --movements."
        )

    print_split_subjects(df, args.reference_split_col, args.reference_split_label, grp_col)
    print(f"\nReference aggregation: {args.aggregation}")
    if args.aggregation == "trimmed_mean":
        print(f"  aggregation_trim_frac: {args.aggregation_trim_frac}")

    # Resolve paths
    def resolve_path(p: str) -> Path:
        pth = Path(str(p))
        if pth.is_absolute():
            return pth
        if args.root_override:
            return Path(args.root_override) / pth
        return pth

    df["csv_path"] = df[path_col].apply(resolve_path)

    # Template neutral: frame 0 dental + fixed rot
    template_path = resolve_path(args.template_csv)
    template_frames = load_facemocap_csv(template_path)
    template_frame0 = template_frames[0:1]  # (1,108,3)
    template_dental, ok = world_to_dental(template_frame0)
    if not ok[0]:
        raise RuntimeError(f"Template dental frame invalid at frame 0: {template_path}")
    Rfix = fixed_rot_xyz(tuple(args.fixed_rot_xyz))
    template_dental0 = (Rfix @ template_dental[0].T).T  # 108x3
    template_face = template_dental0[3:, :]  # 105x3

    # Process per sample
    rng = np.random.default_rng(args.seed)
    facial_slice = slice(3, 108)

    rows = []
    # Store per-movement processed sequences
    by_mov: Dict[str, List[Dict]] = {m: [] for m in wanted}

    for _, r in df.iterrows():
        csv_path = Path(r["csv_path"])
        mov = str(r["mov_norm"]).upper()
        cond = r[grp_col]
        is_healthy = (str(cond).strip().lower() == "healthy")

        rec = dict(
            mov=mov,
            csv=str(csv_path),
            is_healthy=is_healthy,
            reference_split=str(r[args.reference_split_col]),
        )
        try:
            frames_world = load_facemocap_csv(csv_path)
            frames_dental, ok_d = world_to_dental(frames_world)
            rec["dental_ok_frac"] = float(ok_d.mean())
            rec["dental_drift_rms"] = dental_marker_drift(frames_dental)

            neutral_idx = pick_neutral_frame_most_complete(frames_dental, args.neutral_first_pct, facial_slice)
            rec["neutral_idx"] = int(neutral_idx)

            # Apply fixed rot to ALL frames (canonicalize)
            frames_can = (Rfix @ frames_dental.reshape(-1,3).T).T.reshape(frames_dental.shape)

            # Build correspondences for neutral facial points
            Pn = frames_can[neutral_idx, 3:, :]  # 105x3
            Qn = template_face  # 105x3

            valid = np.isfinite(Pn).all(axis=1) & np.isfinite(Qn).all(axis=1)
            rec["n_valid_face"] = int(valid.sum())
            if valid.sum() < args.min_points:
                raise ValueError(f"Not enough valid facial correspondences: {valid.sum()} < {args.min_points}")

            P = Pn[valid]
            Q = Qn[valid]

            if args.ransac:
                R, t, inl, score = trimmed_ransac_rigid(
                    P, Q, trials=args.ransac_trials, subset=args.ransac_subset,
                    trim_frac=args.trim_frac, rng=rng
                )
                rec["trimmed_rms_fit"] = float(score)
                rec["n_inliers"] = int(inl.sum())
                if args.try_yaw_flip:
                    R, t, used_flip, score2 = maybe_yaw_flip(P, Q, R, t, axis=args.yaw_flip_axis)
                    rec["used_yaw_flip"] = bool(used_flip)
                    rec["rms_after_flip"] = float(score2)
                if args.huber_iters > 0:
                    # Recompute residuals and inliers after potential flip
                    res = np.linalg.norm(apply_rt(P, R, t) - Q, axis=1)
                    inl2 = trimmed_indices(res, args.trim_frac)
                    R, t = huber_irls_refine(P, Q, R, t, inl2, iters=args.huber_iters, k=args.huber_k)
            else:
                R, t = kabsch(P, Q)
                rec["trimmed_rms_fit"] = float(rms(np.linalg.norm(apply_rt(P, R, t) - Q, axis=1)))
                rec["n_inliers"] = int(P.shape[0])
                rec["used_yaw_flip"] = False

            # Apply to all frames (facial + dental + everything)
            Tn = frames_can.shape[0]
            flat = frames_can.reshape(Tn*108, 3)
            flat2 = apply_rt(flat, R, t)
            frames_aligned = flat2.reshape(Tn, 108, 3)

            # Movement window by energy from neutral
            E = displacement_energy(frames_aligned, neutral_idx, facial_slice)
            w0, w1 = extract_active_window(E, neutral_idx, thr_percentile=args.energy_thr_percentile, min_len=args.min_window_len)
            rec["win_start"] = int(w0)
            rec["win_end"] = int(w1)

            # Resample to fixed length
            frames_res = resample_sequence_nan_robust(frames_aligned, w0, w1, args.n_frames)
            rec["n_frames_in"] = int(frames_world.shape[0])
            rec["n_frames_win"] = int(w1 - w0 + 1)

            # store
            by_mov[mov].append(dict(
                csv=str(csv_path),
                is_healthy=is_healthy,
                frames_res=frames_res,
                neutral_idx=int(neutral_idx),
                win=(int(w0), int(w1)),
                trimmed_rms=float(rec.get("trimmed_rms_fit", np.nan)),
                n_valid=int(rec.get("n_valid_face", 0)),
            ))

            rec["status"] = "ok"
            rec["error"] = ""
        except Exception as e:
            rec["status"] = "fail"
            rec["error"] = str(e)
        rows.append(rec)

    summary = pd.DataFrame(rows)
    summary_path = out_dir / "summary_sequences.csv"
    summary.to_csv(summary_path, index=False)

    # Compute per-movement healthy reference mean and export animations
    for mov, items in by_mov.items():
        if len(items) == 0:
            continue
        mov_dir = out_dir / mov
        ensure_dir(mov_dir)
        ensure_dir(mov_dir / "diagnostics")

        # All processed items are healthy reference rows by construction.
        healthy = [it["frames_res"] for it in items if it["is_healthy"]]
        if len(healthy) == 0:
            raise RuntimeError(f"No healthy reference samples processed successfully for {mov}.")

        stack = np.stack(healthy, axis=0)  # N,T,108,3
        mean_seq = aggregate_reference_sequences(
            stack,
            method=args.aggregation,
            trim_frac=args.aggregation_trim_frac,
        )  # T,108,3
        envelope = compute_reference_envelope(
            stack,
            center_seq=mean_seq,
            dental_n=args.dental_n,
            low_q=args.envelope_low_quantile,
            high_q=args.envelope_high_quantile,
        )

        np.save(mov_dir / "mean_healthy.npy", mean_seq)
        envelope.to_csv(mov_dir / "reference_envelope_per_marker.csv", index=False)
        np.savez_compressed(
            mov_dir / "reference_stack_and_envelope.npz",
            stack=stack,
            mean_healthy=mean_seq,
            envelope=envelope.to_records(index=False),
        )
        # also CSV: one row per frame, flattened
        mean_flat = mean_seq.reshape(args.n_frames, 108*3)
        mean_csv = mov_dir / "mean_healthy.csv"
        pd.DataFrame(mean_flat).to_csv(mean_csv, index=False, header=False)

        # Interactive animation for mean
        make_animation_html(mean_seq, mov_dir / "mean_healthy_animation.html", title=f"{mov} mean healthy (aligned, no head motion)", facial_only=True)

        # Optionally export a few sample animations
        n_export = min(args.export_sample_anims, len(items))
        for k in range(n_export):
            it = items[k]
            sid = Path(it["csv"]).stem
            make_animation_html(it["frames_res"], mov_dir / f"sample_animation_{sid}.html",
                                title=f"{mov} sample {sid} (aligned, resampled)", facial_only=True)

    # Also export template neutral visualization
    make_animation_html(template_dental0[None, :, :], out_dir / "template_neutral_frame0.html",
                        title="Template neutral (frame 0) in its dental frame (canonicalized)", facial_only=True)

    print(f"[OK] Wrote {summary_path}")
    print(f"[OK] Wrote per-movement outputs under: {out_dir}")

if __name__ == "__main__":
    main()
